Task 7
heckfyxe/test-guru pull request #10
Opened 2020-12-27 09:35 UTC by heckfyxe

2020-12-27 12:35 UTC, VidgarVii requested changes

2020-12-27 12:35 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +      return
до return дело не дойдет. Всё закончится в render

2020-12-27 12:35 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +    if answer_ids.nil?
я кажется понял, что ты имел ввиду. Это такой фикс бага, если ответ не был выбран? В общем это точно не тут надо делать. Контроллер точно за это не отвечает

2020-12-27 12:35 UTC, VidgarVii commented on app/helpers/test_passages_helper.rb
> +end
так как хелперы доступны без костылей только в представлениях, значит они помогают выстроить DOM
Пример. link_to, form_with, content_tag. Вот это всё хелперы. 
Представление ни когда не должно формировать бизнес логику. У тебя для этого есть модели.

2020-12-27 12:41 UTC, heckfyxe commented on app/helpers/test_passages_helper.rb
> +end
Стоит создать отдельную модель для результата без active record?

2020-12-28 12:31 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +  end
если методу find_user дать более подходящее название, например current_user
то текущий метод не много упростится
```
current_user.tests.push(@test)
redirect_to current_user.test_passage(@test)
```

Тогда еще переменную юзера надо будет закешировать, чтобы лишние запросы в БД не шли

@user ||= User.first

А то что юзер первый выбирается пока это норм. Далее подключим аутентификацию. И данный метод уйдет

2020-12-28 12:31 UTC, VidgarVii commented on app/models/test_passage.rb
> +  class Progress
твои попытки абстрагировать логику это конечно похвально. Но тут лучше будет смотреться если просто данные методы положить в модель TestPassage. Критического ни чего не случиться. И правило Деметры не нарушается. 
А вообще советую глянуть паттерн (от дяди Боба) и так же есть гем для него **Интерактор**
Я думаю тебе зайдет

2020-12-28 12:34 UTC, VidgarVii commented on db/fixtures/3_tests.rb
> +          { id: 1, title: 'Ruby для начинающих', level: 0, category_id: 1, author_id: 1 },
id: 1 AR сам растравляет ид согласно текущей таблицы. 
author_id: 1 - нельзя так харкодить id. Безопасней всего обращаться к объектам

2020-12-29 06:11 UTC, merged