Task 3
heckfyxe/test-guru pull request #3
Opened 2020-11-29 21:42 UTC by heckfyxe

Created associations for tables.
seeds.rb create initial db records.
schema.rb is added to rubocop exclude list.
Added tests_by_level method to User class.
Added test_titles_by_category_title class method to Test class.

2020-11-30 13:01 UTC, VidgarVii commented on db/seeds.rb
> +end
Сиды это начальные данные для разработки. Бывает так что нужно прогнать сид в процессе работы. По этому все данные должны быть защищены от дублирования. В данном случаи Если я запущу 10 db:seed, то у меня буде 30 категорий и и.д. Можно например проверять так User.exists?

2020-11-30 13:01 UTC, VidgarVii commented on db/seeds.rb
> +users = User.create([{ first_name: 'Иван', last_name: 'Соловьёв' },
использую bang! методы. create! Чтобы получить ошибку, если что то пойдет не по плану

2020-12-01 06:00 UTC, VidgarVii requested changes

2020-12-01 06:00 UTC, VidgarVii commented on app/models/test.rb
> +        .select(:title).collect(&:title)
можно  без `select(:title).collect(&:title)`
pluck(:title)

2020-12-01 06:00 UTC, VidgarVii commented on app/models/user.rb
> +  def tests_by_level(level)
в названии метода, хорошо бы указать, что это завершенные тесты

2020-12-01 06:00 UTC, VidgarVii commented on db/migrate/20201129192641_create_tables_associations.rb
> +end
что это миграция тут делает?
1 миграции на создание и изменение таблиц должны идти отдельно.
2 add_reference оформлено не верно. Так же нужно указывать, чтобы создавался внешний ключ.

2020-12-01 06:00 UTC, VidgarVii commented on db/seeds.rb
> +users = User.find_or_create_by!([{ first_name: 'Иван', last_name: 'Соловьёв' },
я не уверен что find_or_create_by! так умеет

2020-12-01 11:15 UTC, heckfyxe commented on app/models/user.rb
> +  def tests_by_level(level)
В задание сказано возвращать тесты, "которые проходит или когда-либо проходил Пользователь"

2020-12-01 13:09 UTC, VidgarVii commented on app/models/user.rb
> +  def tests_by_level(level)
вот это и надо указать в названии метода. В данный момент название метода не согласуется со реализацией метода

2020-12-02 19:51 UTC, merged